---
# Example: Redis Cluster with ACL from PVC
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisCluster
metadata:
  name: redis-cluster-acl-pvc
spec:
  clusterSize: 3
  kubernetesConfig:
    image: quay.io/opstree/redis:latest
    imagePullPolicy: IfNotPresent
  # ACL configuration from PVC
  # The operator mounts the PVC at /data/redis, so Redis reads /data/redis/user.acl
  # Make sure the PVC contains a file named "user.acl" with Redis ACL rules
  acl:
    persistentVolumeClaim: "redis-acl-pvc"
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
  redisLeader:
    replicas: 3
  redisFollower:
    replicas: 3
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
