---
apiVersion: v1
description: Provides easy redis setup definitions for Kubernetes services, and deployment.
engine: gotpl
maintainers:
  - name: Opstree Solutions
name: redis-operator
sources:
  - https://github.com/OT-CONTAINER-KIT/redis-operator
version: 0.2
home: https://github.com/OT-CONTAINER-KIT/redis-operator
icon: https://github.com/OT-CONTAINER-KIT/redis-operator/raw/master/static/redis-operator-logo.svg
keywords:
- operator
- redis
- opstree
- kubernetes
- openshift
