linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8
  gofmt:
    simplify: true

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - decorder
    - dogsled
    - durationcheck
    - errcheck
    - errname
    - exportloopref
    - gci
    - gochecknoinits
    - gofmt
    - gofumpt
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - makezero
    - misspell
    - noctx
    - nolintlint
    - nosprintfhostport
    - staticcheck
    - tenv
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unused
    - wastedassign
    - whitespace

run:
  timeout: 15m
  go: "1.21"
  tests: true
  show-stats: true
  skip-files:
    - ".+\\.generated.go"

output:
  format: colored-line-number
  sort-results: true
  print-linter-name: true
  print-issued-lines: true