linters-settings:
  gofmt:
    simplify: true

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - decorder
    - dogsled
    - durationcheck
    - errcheck
    - errname
    - exportloopref
    - gci
    - gochecknoinits
    - gofmt
    - gofumpt
    - goprintffuncname
    - gosimple
    - govet
    - grouper
    - importas
    - ineffassign
    - makezero
    - misspell
    - noctx
    - nolintlint
    - nosprintfhostport
    - staticcheck
    - tenv
    - thelper
    - tparallel
    - unconvert
    - unused
    - wastedassign
    - whitespace

run:
  timeout: 15m
  go: "1.23.4"
  tests: true

output:
  sort-results: true
  print-linter-name: true
  print-issued-lines: true