linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0.8 
  gofmt:
    simplify: true

# linters:
#   enable-all: true
#   disable:
#     - errcheck 
#     - tagliatelle
# Exclude the files that are causing the errors
issues:
  exclude-rules:
    - path: _test\.go # Ignore test files for linting
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
run:
  timeout: 5m
  go-version: "1.21"
  test: false
  # Exclude third-party packages and go.mod from the lint checks
  exclude: |
    '(^vendor/.*|.*_test\.go|go\.mod|.*validatingwebhookconfiguration\.go|.*mutatingwebhookconfiguration\.go)'
  skip-files:
    - '^.*validatingwebhookconfiguration\.go$'
    - controllers/suite_test.go
  skip-dirs:
    - k8s.io/client-go
    - github.com/banzaicloud/k8s-objectmatcher
    - github.com/go-logr/logr
    - github.com/go-redis/redis
    - github.com/onsi/ginkgo
    - github.com/onsi/gomega
    - github.com/pkg/errors
    - k8s.io/api
    - k8s.io/apimachinery
    - sigs.k8s.io/controller-runtime
    - golang.org/x/sys
    - vendor$, third_party$, testdata$, examples$, Godeps$, builtin$