extends: default

rules:
  line-length:
    max: 200
    level: warning
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  comments-indentation: disable

ignore:
  - resources.yaml