apiVersion: kuttl.dev/v1beta1
kind: TestSuite
startKIND: true
kindConfig: "./kind-config.yaml"
crdDir: "./config/crd/bases"
testDirs:
  - "./tests/e2e/"
parallel: 1
timeout: 60
kindContainers:
  - operator:test
namespace : ot-container
suppress :
  - events