apiVersion: v1
data:
  user.acl: dXNlciBvcHN0cmVlIG9uIH4qICYqICtAYWxsID5hYmNAMTIzCnVzZXIgYnVpbGRwaXBlciBvbiB+KiAmKiArQGFsbCA+YWJjQDEyMwo=
kind: Secret
metadata:
  name: acl-secret
  namespace: default
type: Opaque