apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name : {{ .Values.redisOperator.name }}
    helm.sh/chart : {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by : {{ .Release.Service }}
    app.kubernetes.io/instance : {{ .Release.Name }}
    app.kubernetes.io/version : {{ .Chart.AppVersion }}
    app.kubernetes.io/component: webhook
    app.kubernetes.io/part-of : {{ .Release.Name }}
  name: {{ .Values.service.name }}
  namespace:  {{ .Release.Namespace }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    name: {{ .Values.redisOperator.name }}
