{{- if eq .Values.externalConfig.enabled true }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "redis.name" $ }}-ext-config
  labels:
    {{- include "common.labels" $ | nindent 4 }}
data:
  redis-additional.conf: |
    {{ .Values.externalConfig.data | nindent 4 }}
{{- end }}
