{{- $followerReplicas := include "redis.replicas" (dict "replicas" .Values.redisCluster.follower.replicas "clusterSize" .Values.redisCluster.clusterSize) }}
{{- if and (gt (int $followerReplicas) 0) (eq .Values.externalService.enabled true) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redisCluster.name | default .Release.Name }}-follower-external-service
{{- if .Values.externalService.annotations }}
  annotations:
{{ toYaml .Values.externalService.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
spec:
  type: {{ .Values.externalService.serviceType }}
  selector:
    app: {{ .Values.redisCluster.name | default .Release.Name }}-follower
    redis_setup_type: cluster
    role: follower
  ports:
    - protocol: TCP
      port: {{ .Values.externalService.port }}
      targetPort: 6379
      name: client
{{- end }}
