{{- $leaderReplicas := include "redis.replicas" (dict "replicas" .Values.redisCluster.leader.replicas "clusterSize" .Values.redisCluster.clusterSize) }}
{{- if and (gt (int $leaderReplicas) 0) (eq .Values.externalService.enabled true) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis.name" $ }}-leader-external-service
{{- if .Values.externalService.annotations }}
  annotations:
{{ toYaml .Values.externalService.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
spec:
  type: {{ .Values.externalService.serviceType }}
  selector:
    app: {{ include "redis.name" $ }}-leader
    redis_setup_type: cluster
    role: leader
  ports:
    - protocol: TCP
      port: {{ .Values.externalService.port }}
      targetPort: 6379
      name: client
{{- end }}
