---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: default
data:
  redis.conf: |
    bind 0.0.0.0
    port 6379
    timeout 0
    tcp-keepalive 300
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-scripts
  namespace: default
data:
  backup.sh: |
    #!/bin/bash
    echo "Redis backup script"
    redis-cli --rdb /data/backup/dump.rdb
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sentinel-config
  namespace: default
data:
  sentinel.conf: |
    sentinel deny-scripts-reconfig yes
    sentinel resolve-hostnames yes
    sentinel announce-hostnames yes
