---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisSentinel
metadata:
  name: redis-sentinel
spec:
  clusterSize: 3
  kubernetesConfig:
    image: quay.io/opstree/redis-sentinel:v7.0.12
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 101m
        memory: 128Mi
      limits:
        cpu: 101m
        memory: 128Mi
    additionalVolumes:
      - name: sentinel-config
        configMap:
          name: sentinel-config
      - name: sentinel-logs
        emptyDir: {}
    additionalVolumeMounts:
      - name: sentinel-config
        mountPath: /etc/sentinel
        readOnly: true
      - name: sentinel-logs
        mountPath: /var/log/sentinel
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
  redisSentinelConfig:
    redisReplicationName: redis-replication
    redisPort: "6379"
    quorum: "2"
    parallelSyncs: "1"
    failoverTimeout: "180000"
    downAfterMilliseconds: "30000"
