# permissions for end users to view redissentinels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: redissentinel-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: redis-operator
    app.kubernetes.io/part-of: redis-operator
    app.kubernetes.io/managed-by: kustomize
  name: redissentinel-viewer-role
rules:
- apiGroups:
  - redis.redis.opstreelabs.in
  resources:
  - redissentinels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - redis.redis.opstreelabs.in
  resources:
  - redissentinels/status
  verbs:
  - get
