apiVersion: v1
kind: Pod
metadata:
  name: kubectl-pod
  namespace: default
spec:
  serviceAccountName: internal-kubectl
  containers:
  - name: kubectl-container
    image: shubham192001/backup-user:latest
    command: ["sleep", "3600"]
