---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: RedisReplication
metadata:
  name:  redis-replication
spec:
  clusterSize: 3
  podSecurityContext:
    runAsUser: 1000
    fsGroup: 1000
  # redisConfig:
  #   additionalRedisConfig: redis-external-config
  kubernetesConfig: 
    image: quay.io/opstree/redis:v7.0.12
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 101m
        memory: 128Mi
      limits:
        cpu: 101m
        memory: 128Mi
    redisSecret:
      name: redis-secret
      key: password
    # imagePullSecrets:
    #   - name: regcred
  env:
  - name: CUSTOM_ENV_VAR_1
    value: "custom_value_1"
  - name: CUSTOM_ENV_VAR_2
    value: "custom_value_2"   
  storage:
    volumeClaimTemplate:
      spec:
        # storageClassName: standard
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi