apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster
metadata:
  labels:
    app.kubernetes.io/name: rediscluster
    app.kubernetes.io/instance: rediscluster-sample
    app.kubernetes.io/part-of: redis-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: redis-operator
  name: rediscluster-sample
spec:
  # TODO(user): Add fields here
