---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-replication
    redis_setup_type: replication
    role: replication
  name: redis-replication
spec:
  ports:
    - name: redis-client
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis-replication
    redis_setup_type: replication
    role: replication
    # type: LoadBalancer
  type: NodePort
