---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-standalone
    redis_setup_type: standalone
    role: standalone
  name: redis-standalone
spec:
  ports:
  - name: redis-client
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-standalone
    redis_setup_type: standalone
    role: standalone
# type: LoadBalancer
  type: NodePort
