---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redisOperator.name }}
  labels:
    control-plane: "{{ .Values.redisOperator.name }}"
    app.kubernetes.io/name: {{ .Values.redisOperator.name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: {{ .Values.redisOperator.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.redisOperator.name }}
    spec:
      containers:
      - name: "{{ .Values.redisOperator.name }}"
        image: "{{ .Values.redisOperator.imageName }}:{{ .Values.redisOperator.imageTag }}"
        imagePullPolicy: {{ .Values.redisOperator.imagePullPolicy }}
        command:
        - /manager
        args:
        - --leader-elect
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- end }}
      serviceAccountName: "{{ .Values.serviceAccountName }}"
      serviceAccount: "{{ .Values.serviceAccountName }}"
