---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redisOperator.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.redisOperator.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.redisOperator.name }}
    spec:
      serviceAccountName: {{ .Values.redisOperator.name }}
      containers:
      - name: "{{ .Values.redisOperator.name }}"
        image: "{{ .Values.redisOperator.imageName }}:{{ .Values.redisOperator.imageTag }}"
        imagePullPolicy: {{ .Values.redisOperator.imagePullPolicy }}
        env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: OPERATOR_NAME
            value: "{{ .Values.redisOperator.name }}"
