---
apiVersion: redis.redis.opstreelabs.in/v1beta1
kind: RedisCluster 
metadata:
  name: redis-cluster-1
spec:
  clusterSize: 3
  kubernetesConfig:
    kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.5
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 101m
        memory: 128Mi
      limits:
        cpu: 101m
        memory: 128Mi
    # redisSecret:
    #   name: redis-secret
    #   key: password
    # imagePullSecrets:
    #   - name: regcred
  storage:
    volumeClaimTemplate:
      spec:
        # storageClassName: standard
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

