apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backup-role-binding
subjects:
  - kind: ServiceAccount
    name: backup-service-account
roleRef:
  kind: Role
  name: modify-pods
  apiGroup: rbac.authorization.k8s.io