# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/redis.redis.opstreelabs.in_redis.yaml
- bases/redis.redis.opstreelabs.in_redisclusters.yaml
- bases/redis.redis.opstreelabs.in_redisreplications.yaml
- bases/redis.redis.opstreelabs.in_redissentinels.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [CERTMANAGER] To enable cert-manager, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
- patches/cainjection_in_redis.yaml
- patches/cainjection_in_redisclusters.yaml
- patches/cainjection_in_redisreplications.yaml
- patches/cainjection_in_redissentinels.yaml

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
