---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-cluster-leader
    redis_setup_type: cluster
    role: leader
  name: redis-cluster-leaders
spec:
  ports:
    - name: redis-client
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis-cluster-leader
    redis_setup_type: cluster
    role: leader
    # type: LoadBalancer
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-cluster-follower
    redis_setup_type: cluster
    role: follower
  name: redis-cluster-followers
spec:
  ports:
    - name: redis-client
      port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis-cluster-follower
    redis_setup_type: cluster
    role: follower
    # type: LoadBalancer
  type: NodePort
