name: Auto Create Release On Tag

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Get version
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          echo "TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Check if release exists
        id: check_release
        run: |
          RELEASE_EXISTS=$(gh release view ${{ steps.get_version.outputs.VERSION }} --json id 2>/dev/null | jq -r '.id' || echo "")
          if [ -n "$RELEASE_EXISTS" ] && [ "$RELEASE_EXISTS" != "null" ]; then
            echo "Release already exists, skipping creation"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Release does not exist, will create it"
            echo "exists=false" >> $GITHUB_OUTPUT
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release notes
        id: release_notes
        if: steps.check_release.outputs.exists == 'false'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PREVIOUS_TAG=$(git describe --tags --abbrev=0 ${{ steps.get_version.outputs.VERSION }}^ 2>/dev/null || git rev-list --max-parents=0 HEAD)

          CHANGELOG=""
          declare -A SEEN_PRS

          while IFS= read -r line; do
            commit_hash=$(echo "$line" | cut -d' ' -f1)
            commit_msg=$(echo "$line" | cut -d' ' -f2-)

            # Prefer author login from associated PR
            pr_json=$(gh api repos/${{ github.repository }}/commits/$commit_hash/pulls -H "Accept: application/vnd.github+json" 2>/dev/null || true)
            pr_number=$(echo "$pr_json" | jq -r '.[0].number // empty')
            if [ -n "$pr_number" ] && [ -z "${SEEN_PRS[$pr_number]+x}" ]; then
              pr_title=$(echo "$pr_json" | jq -r '.[0].title // empty')
              pr_author=$(echo "$pr_json" | jq -r '.[0].user.login // empty')
              if [ -z "$pr_author" ] || [ "$pr_author" = "null" ]; then
                pr_author="unknown"
              fi
              CHANGELOG="$CHANGELOG* ${pr_title:-$commit_msg} (#$pr_number) (@$pr_author)"$'\n'
              SEEN_PRS[$pr_number]=1
            else
              # No PR associated: include commit message without PR info
              CHANGELOG="$CHANGELOG* $commit_msg"$'\n'
            fi
          done < <(git log --pretty=format:"%H %s" ${PREVIOUS_TAG}..${{ steps.get_version.outputs.VERSION }})

          cat > release_notes.md << EOF
          ## Changes
          ${CHANGELOG}
          EOF
      
      - name: Create GitHub Release
        if: steps.check_release.outputs.exists == 'false'
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.get_version.outputs.VERSION }}
          body_path: release_notes.md
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}