name: E2E
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master  

env:
  ImageName: redis-operator
  ImageTag: test

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.5.0
        with:
          config: "./tests/_config/kind-config.yaml"

      - name: Extract and encode kubeconfig from kind
        run: |
          kubectl config view --minify --flatten > ./kubeconfig.yml
          echo "KUBE_CONFIG_DATA=$(cat ./kubeconfig.yml | base64 | tr -d '\n')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64
          push: false
          tags: ${{ env.ImageName }}:${{ env.ImageTag }}

      - name: Set up Helm
        uses: azure/setup-helm@v3.5
        with:
          version: v3.11.2

      - name: Deploy Redis Operator with Helm
        run: |
            helm repo add ot-helm https://ot-container-kit.github.io/helm-charts/
            helm repo update
            helm install --create-namespace --namespace=ot-container redis-operator ot-helm/redis-operator \
            --set redisOperator.imageName=${{ env.ImageName }} \
            --set redisOperator.imageTag=${{ env.ImageTag }} \
            --set redisOperator.imagePullPolicy=Never --wait --timeout 5m

      - name: Show Pods - DEBUG
        run: |
          kubectl get pods -n ot-container

      - name: Install kuttl
        run: |
          curl -L https://github.com/kudobuilder/kuttl/releases/download/v0.15.0/kubectl-kuttl_0.15.0_linux_x86_64 -o /usr/local/bin/kuttl
          chmod +x /usr/local/bin/kuttl

      - name: Run e2e test
        run: |
          kuttl test --config ./tests/_config/kuttl-test.yaml