name: E2E
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master  

env:
  Image: operator:test

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build multi-arch image
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/arm64,linux/amd64
          push: false
          tags: ${{ env.Image }}

      - name: Install kuttl
        run: |
          
          curl -L https://github.com/kudobuilder/kuttl/releases/download/v0.15.0/kubectl-kuttl_0.15.0_linux_x86_64 -o /usr/local/bin/kuttl
          
          chmod +x /usr/local/bin/kuttl

      - name: Run e2e test
        run: |
          kuttl test