name: E2E
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master  

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install kuttl
        run: |
          
          curl -L https://github.com/kudobuilder/kuttl/releases/download/v0.15.0/kubectl-kuttl_0.15.0_linux_x86_64 -o /usr/local/bin/kuttl
          
          chmod +x /usr/local/bin/kuttl

      - name: Run e2e test
        run: |
          kuttl test